Step3
mariimeireles/ChuckNorrisFacts pull request #3
Opened 2018-03-26 17:50 UTC by mariimeireles

2018-03-27 17:14 UTC, ubiratansoares requested changes
Deixei comentários :)

2018-03-27 17:14 UTC, ubiratansoares commented on ChuckNorrisFacts/Cartfile.resolved
> +github "RxSwiftCommunity/RxAlamofire" "8a4856ddd77910950aa2b0f9e237e0209580503c"
Tem algum motivo em particular para usar esse commit do RxAlamofire? 👀

2018-03-27 17:14 UTC, ubiratansoares commented on ChuckNorrisFacts/ChuckNorrisFacts/ChuckFact/Infra/BadRequestError.swift
> +    init(code: Int) {
Pq  nós não poderíamos ter um único `enum` representativo de qualquer erro de REST?

Por exemplo : 

```swift
enum RestError {
    case notFound
    case remoteServerDown
    case clientError(Int)
    
    init(code: Int) {
        switch code {
        case 404:
            self = .notFound
        case 500...513:
            self = .remoteServerDown
        default:
            self = .clientError(code)
        }
    }
}
```

2018-03-27 17:14 UTC, ubiratansoares commented on ChuckNorrisFacts/ChuckNorrisFacts/ChuckFact/Infra/JSONParseError.swift
> +    case result
Não sei se entendi o sentido desse `enum`? 🤔

2018-03-27 17:14 UTC, ubiratansoares commented on ChuckNorrisFacts/ChuckNorrisFacts/ChuckFact/Infra/ServiceError.swift
> +    case `internalServer`
Que tal nós usarmos algum nome não reservado para a linguagem nesse `case`? 😄

2018-03-27 17:14 UTC, ubiratansoares commented on ChuckNorrisFacts/ChuckNorrisFacts/ChuckFact/Web Service/JSON.swift
> +typealias JSON = [String: Any?]
👀

2018-03-27 17:14 UTC, ubiratansoares commented on ChuckNorrisFacts/ChuckNorrisFactsTests/Infra/InfraHandlerTests.swift
> +        let response = getResponseFor(statusCode: 422)
Essa linha

```swift
let response = getResponseFor(statusCode: XYZ)
```

que é executada a cada teste, não é equivalente a criar uma nova instância de `response` dentro de setUp( )? 👀

2018-03-27 17:14 UTC, ubiratansoares commented on ChuckNorrisFacts/ChuckNorrisFacts/ChuckFact/Model/FactModel.swift
> +        if let categories = fact.categories, let category = categories.categories?.first {
É certeza de que `Fact` pode estar associado a mais de uma `Category`? 👀

2018-03-27 17:14 UTC, ubiratansoares commented on ChuckNorrisFacts/ChuckNorrisFacts/ChuckFact/Web Service/FactWebService.swift
> +        let urlMaker = FactURLMaker()
Esse urlMaker não poderia ser constante na classe?

2018-03-27 17:14 UTC, ubiratansoares commented on ChuckNorrisFacts/ChuckNorrisFacts/ChuckFact/Web Service/FactWebService.swift
> +        return RxAlamofire.request(.get, url)
Tem algum motivo para não pedir `requestJSON` direto? 👀

2018-03-27 22:23 UTC, mariimeireles commented on ChuckNorrisFacts/ChuckNorrisFacts/ChuckFact/Model/FactModel.swift
> +        if let categories = fact.categories, let category = categories.categories?.first {
no JSON category tem o valor de um array, e quase certeza que eu já vi mais de uma categoria para um Fact

2018-03-28 13:31 UTC, ubiratansoares commented on ChuckNorrisFacts/ChuckNorrisFacts/ChuckFact/Web Service/JSON.swift
> +typealias JSON = [String: Any?]
👏

2018-04-02 13:45 UTC, ubiratansoares approved these changes

2018-04-02 18:32 UTC, merged